name: Lint code

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check
      uses: astral-sh/ruff-action@v3
      with:
        args: check --extend-select I .
    - name: format
      uses: astral-sh/ruff-action@v3
      with:
        args: format .
